version: '3'

services:
  mongo:
    image: mongo:4.4
    restart: always
    container_name: "mongodb"
    working_dir: "/database/"
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
    volumes:
      - "./database/:/data/db"

  job-service:
    restart: 'unless-stopped'
    container_name: 'job-service'
    build:
      context: 'job_manager'
      dockerfile: 'docker/Dockerfile'
    command: 'python api/main.py'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
    depends_on:
      - 'mongo'

  worker-launcher:
    restart: 'unless-stopped'
    container_name: 'worker-launcher'
    build:
      context: 'ml_worker'
      dockerfile: 'docker/Dockerfile_arm64'
    command: 'python3 src/worker_launcher.py'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./ml_worker:/app"
    environment:
      NUM_PROCESSORS: 2
      NETWORK: 'computing_api_default'
      HOST: '{"nickname":"local", 
              "hostname":"local.als.lbl.gov",
              "frontend_constraints": {"num_processors":10, "num_gpus":0, "list_gpus":[], "num_nodes":2},
              "backend_constraints":{"num_processors":10, "num_gpus":0, "list_gpus":[], "num_nodes":2}}'
      WORKER_IMAGE: 'mlexchange1/dummy-worker:1.0'
    depends_on:
      - 'job-service'

  front-end:
    restart: "unless-stopped"
    container_name: "comp-frontend"
    build:
      context: "front_end"
      dockerfile: "docker/Dockerfile"
    command: "python frontend.py"
    ports:
      - "127.0.0.1:8050:8050"
    depends_on:
      - 'job-service'

networks: 
  default:
    name: "computing_api_default"