version: '3'

services:
  job-service:
    restart: 'unless-stopped'
    container_name: 'job-service'
    build:
      context: 'job_manager'
      dockerfile: 'docker/Dockerfile'
    command: 'python api/main.py'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
    depends_on:
      - 'mongo'
    ports:
      - '8080:8080'

  worker-launcher:
    restart: 'unless-stopped'
    container_name: 'worker-launcher'
    build:
      context: 'ml_worker'
      dockerfile: 'docker/Dockerfile_arm64'
    command: sh -c '
      sleep 20 &&
      python3 src/worker_launcher.py'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./ml_worker:/app"
    environment:
      NUM_PROCESSORS: '${NUM_PROCESSORS}'
      NETWORK: '${COMPOSE_PROJECT_NAME}_default'
      HOST: '${HOST}'
    depends_on:
      - 'job-service'

  mongo:
    image: mongo:4.4
    restart: always
    container_name: "mongodb"
    working_dir: "/database/"
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
    volumes:
      - "./database/:/data/db"
    ports:
      - "27017:27017"
