version: '3'

services:
    nginx:
        build:
            context: './docker' #need to specify context if pointing to specific dockerfile
            dockerfile: 'nginx.docker'
        ports:
            - "8080:80"
        depends_on:
            - dash_app
    dash_app:
        build: './docker/'
        volumes:
            - "${PWD}:/app/work/"
            - "${PWD}/../data/:/app/data"
        expose:
            - '8050'
        restart: always
        ulimits:
            memlock: -1
            stack: 67108864
        shm_size: '1g'
        

